spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:9001
              predicates:
                - Path= /api/v1/auth/**
            - id: order-service
              uri: http://localhost:8080
              predicates:
                - Path= /api/v1/orders/**
server:
  port: 9000

