spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/permissiondb
    username: postgres
    password: postgres
    generate-ddl: true
  sql:
    init:
      mode: always

server:
    port: 9003

